version: "1"
# x-variables:
#   dat_auth: &dat_auth auth
#   dat_backend: &dat_backend dat-backend
#   dat_admin: &dat_admin admin
services:
  core-cs:
    container_name: nis_backend_core
    # image: nis-backend
    image: eadinterra/nis-backend
    build:
      context: .
      args:
        - APP=core
        - PORT=${BASE_PORT}
    restart: unless-stopped
    ports:
      - ${BASE_PORT}:${BASE_PORT}
    env_file:
      - .env
    # volumes:
    #   - .:/app
    command: >
      sh -c "pnpm run db:migrate:all && pnpm run db:generate:all && pnpm run start:${ENV}"
    # depends_on:
    #   - redis
  auth-cs:
    container_name: nis_backend_auth
    # image: nis-backend
    image: eadinterra/nis-backend
    build:
      context: .
      args:
        - APP=auth
        - PORT=${AUTH_PORT}
    restart: unless-stopped
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    env_file:
      - .env
    # volumes:
    #   - .:/app # in dev (for real-time updates)
    command: >
      sh -c "pnpm run db:migrate:all && pnpm run db:generate:all && pnpm run start:${ENV} auth"
  # redis:
  #   container_name: nis_backend_redis
  #   image: redis:6.2-alpine
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --save 20 1 --loglevel warning
  #   volumes: 
  #     - ./redis:/data